### ISSUE TITLE
Non-ASCII characters in OME XML metadata causes rename_tiff_channels to fail 

### ISSUE THREAD

**Issue by CameronFRWatson** [goeckslab/tools-mti#83]
Since the update to `tifffile` in the mti-utils docker image in https://github.com/goeckslab/tools-mti/pull/82, `rename_tiff_channels.xml` has been failing with the following error: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tifffile/tifffile.py", line 11543, in overwrite
    value = value.encode('ascii')
            ^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xb5' in position 522: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/efs/fs1/cancer-usegalaxy-shared/database/jobs/075/75759/configs/tmpdv0gnsig", line 46, in <module>
    tiffcomment(os.path.join(cwd, 'renamed_image.ome.tiff'), updated_ome_xml)
  File "/usr/local/lib/python3.11/site-packages/tifffile/tifffile.py", line 24458, in tiffcomment
    tag.overwrite(comment)
  File "/usr/local/lib/python3.11/site-packages/tifffile/tifffile.py", line 11545, in overwrite
    raise ValueError(
ValueError: TIFF strings must be 7-bit ASCII
```

I didn't catch this in testing because the small test data didn't happen to have units specified for the physical distance, which typically contains a non-ASCII character: 

`PhysicalSizeXUnit="µm"`

Luckily there's a seemingly simple fix found here: https://github.com/cgohlke/tifffile/issues/233

Will push a fix soon

**Comment by CameronFRWatson** [comment]
Fixed in https://github.com/goeckslab/tools-mti/pull/84
